### ISSUE TITLE
Activate snail by default with a customize seconds threshold

### ISSUE THREAD

**Issue by omry** [hackebrot/pytest-snail#1]
Hi, thanks! this plugin seems very useful.

Looking at the docs, this does not seem possible:

1. I want to have snail activated automatically unless I deactivate it so users get fast tests normally.
2. I want to manually mark specific tests as slow.

I have some tests that suites that runs many tests (parametrized). each one of them individually is not that slow but the whole sweep is. I would like to mark that entire thing as slow.
is it possible with this plugin?

**Comment by hackebrot** [comment]
Hi @omry! 👋 

Thanks for the feedback! Much appreciated.

As to your first question, I suppose you could write a local plugin that deselects marked tests by default unless you set a custom CLI option. Check out the "Write plugin to deselect slow tests by default" section in my blog post https://raphael.codes/blog/customizing-your-pytest-test-suite-part-2/. 📝 

As to your second question, you can manually add a snail marker to slow tests. If the test uses parametrize pytest applies that marker to every item:

```python
@pytest.mark.snail
@pytest.mark.parametrize(
    "group",
    [
        pytest.param("small_group"),
        pytest.param("large_group"),
        pytest.param("no_pandas_group"),
    ],
    indirect=True,
)
def test_earth(group, event):
    for adventurer in group:
        event.invite(adventurer)

    for attendee in event.attendees:
        attendee.get_ready()
        attendee.travel_to(event)

    event.start()
```

**Comment by omry** [comment]
1. This seems generally useful. although maybe there should be opt in via configuration as it changes the default behaviour of pytest significantly.
Would you consider this kind of functionality for the snail plugin?

2. Will try it out, thanks!

**Comment by hackebrot** [comment]
No, I think it makes sense to maintain this functionality in a separate plugin.
